site_name: SOP de ventas by David Novo
theme:
  name: material
  palette:
    scheme: slate
    primary: cyan
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
nav:
  - Inicio: index.md
  - Equipo de ventas:
    - Appointment Setting:
      - Setting: setting.md
      - Triage: triage.md
    - Closing de ventas:
      - Closing: closing.md
      - Manejo de Objeciones: manejoObjeciones.md

  - Herramientas de ventas:
    - Presentaci√≥n de ventas: presentacionVentas.md
    - Formulario cliente nuevo: formularioClienteNuevo.md
    - Links de pago: linksPago.md

  - Uso del sistema:
    - Calendarios: calendarios.md
    - Conversaciones: conversaciones.md
    - Pipeline: pipeline.md
